title: "Kankakee Community College"
site_name: "Library"
public-url: "https://library.kcc.edu" ## This gets generated into the link that displays in the footer (the one above the social icons)
url: 'https://library.kcc.edu' ## NO TRAILING SLASHES!!/<--nope
timezone: America/Chicago
port: 3000
theme: "kcc-gem-theme"
google-tag_key: GTM-N73VC4W
#core_site: true
#translate: true ## Uncomment to activate Google Translate Powers!!
nav_links:
  - link_text: Tutoring
    link_href: tutoring
    button: false
  - link_text: Policies
    link_href: 'policies'
    button: false
  - link_text: About
    link_href: 'about'
    button: false
  - link_text: Faculty Resources
    link_href: 'https://kcc.libguides.com/facultyservices'
    external: true
    button: false
  - link_text: Contact
    link_href: '#contact'
    button: false
    external: false
  - link_text: Get Help
    link_href: 'https://kcc.libguides.com/canvas'
    external: true
    button: true
#  - link_text: Example External Link
#    link_href: 'https://example-external-link.com'
#    button: false
#    external: true  <---- #### Add the `external: true` key & value to make an external link ####
#
#### Example sub-nav configuration below #### ======================================================= #
##                                                                                                   ##
##   link_href's must have a single '/' in the link (no '/' in the begining or end of the string)    ##
##                                                                                                   ##
## ================================================================================================== #
#
#sub-nav_links:
#  - link_text: Sheets
#    link_href: 'reference/gsheets'
#  - link_text: CloudCannon
#    link_href: 'reference/cloudcannon'
#
collections:
  contacts:
    output: false
  accordions:
    output: false
  icons:
    output: false
    sort_by: 'order'
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    permalink: /:categories/:title/
    baseurl: ../../../
    categories: news
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

include:
  - "_accordions/"
  - "_icons/"

exclude:
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "webpack.config.js"
  - "siteicon.png"
  - "page-startups"
  - "buildtools/"
  - "postcss.config.js"

uploads_dir: # specifies the default uploads directory for CloudCannon
  - "uploads/"

_comments:
  description: "Descriptions are seen by search engines like Google and displayed in search results"

_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
  translate:
    hidden: true # Prevent CloudCannon Users from randomly turning translate on in their site.
  sheet_key:
    hidden: true
  content:
    format: p h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    underline: true
    subscript: true
    superscript: true
    indent: true
    outdent: true
    image: true
    table: true
    left: align-left
    center: center-this-text
    right: align-right
    removeformat: true
    link: true
    numberedlist: true
    bulletedlist: true
    undo: true
    redo: true
    styles: /assets/css/content.css
  _block:
    format: p h2 h3 h4 h5 h6 pre address
    bold: true
    italic: true
    underline: true
    subscript: true
    superscript: true
    indent: true
    outdent: true
    image: true
    table: true
    left: align-left
    center: center-this-text
    right: align-right
    removeformat: true
    link: true
    numberedlist: true
    bulletedlist: true
    undo: true
    redo: true
    styles: /assets/css/content.css
  _text:
    bold: true
    italic: true
    removeformat: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    subscript: true
    superscript: true
_explore:
  groups:
    - heading: 'Standalone | File Browser'
      collections:
        - pages
    - heading: 'Collections | Data'
      collections:
        - contacts
        - accordions